language: node_js
node_js:
  - node
cache: npm
install:
  - npm ci
script:
  - npm test
deploy:
  - cleanup: false
    provider: heroku
    api_key:
      secure: VmYFwWOpZULicwTTHGQYrVObH9uCjhDQVot2dUdueGSsgEqVq3/soTAYlIauWl1BJ1IqcA2PHVknLzb9h8jBwwYYbFD/KNG0GGvDTrhkGVB4Lbj9PXiNZWofxulSSy7mNWZ0m0EmaGhXiYJbOAyX1a4aDODYNhSVuUvfOlaiabYabGk2HPGqYmtE7ecEAlFA8DMI4Jz2ZgwhUsBNvcJwmN/FsL02npQmv7uSUFmcqgkJ9tuK1Mr0td7/BXIKmkEZiEZLpmpq3Yh0WgMlm9vs8iQkaTuhlYhW147x3m5bJf7XufGFl7TH95LguEXIGe3g97nvNQskWikNGLrf16o9oLxIhcgt0XeEoyAovtOMQYayW/4Sh5oP5f+LuHrFx/e+sMAAHLUOIv2v0syFM0STn4ZzmfzrHNbhM8CYmwAo9gIrS/fwAtbdgbzqqngDgQEIe2rpCi+L7qvoS7Xqg6/B4OwoUHNkl3EZbKVwax76ZuuVNGXxllvafSuFIScFQvzsB0OOmtmc1DYgc0mbW9JUT5BIgkUwQBeABrksGNm9JCFQOHcMLThTwUJnAEoId/9OqRf+Eyl4Qo3ls04PYkHPv7U+RgYUq7kMgL6GGtkjMKr9pnkTrOKnKc93mzAXqW6+9L7vUegViRWuE5tur6V5+QWuwIXk8MOhV9aJQIXfAcM=
    app: howmies-api-develop
    on:
      repo: Howmies/howmies-api
      branch: develop
