language: node_js
node_js:
  - node
cache: npm
install:
  - npm ci
script:
  - echo "skipping tests"
deploy:
  - cleanup: false
    provider: heroku
    api_key:
      secure: HEROKU_SECUREKEY
    app: howmies-api-develop
    on:
      repo: Howmies/howmies-api
      branch: develop
